version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: bash /scripts/deploy/api_deploy_dev.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/backend
      - ./scripts:/scripts
      - ./firebase.json:/backend/downtownapi/firebase.json
    environment:
      - SENDGRID_KEY=$SENDGRID_KEY
      - PRODUCTION=False
      - STRIPE_KEY=$STRIPE_KEY
      - STRIPE_WEBHOOK_KEY=$STRIPE_WEBHOOK_KEY
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
      - CURRENT_ROUND=1
      - FIREBASE_KEY=$FIREBASE_KEY
      - FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
      - FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL
      - FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
      - FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET
      - FIREBASE_MEASUREMENTID=$FIREBASE_MEASUREMENTID
      - FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID
      - FIREBASE_APPID=$FIREBASE_APPID
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - BACKEND_URL=$BACKEND_URL
      - FRONTEND_URL=$FRONTEND_URL
      - SUPPORT_EMAIL=$SUPPORT_EMAIL
      - CORS_ALLOWED_ORIGINS=$CORS_ALLOWED_ORIGINS
      - ALLOWED_HOSTS=$ALLOWED_HOSTS
      - ADD_BUSINESS_CSV_TOKEN=$ADD_BUSINESS_CSV_TOKEN

  web:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    command: yarn start
    volumes:
    - ./frontend/src:/frontend/src
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - REACT_APP_FIREBASE_KEY=$FIREBASE_KEY
      - REACT_APP_FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
      - REACT_APP_FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL
      - REACT_APP_FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
      - REACT_APP_FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET
      - REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID
      - REACT_APP_FIREBASE_APPID=$FIREBASE_APPID
      - REACT_APP_FIREBASE_MEASUREMENTID=$FIREBASE_MEASUREMENTID
      - REACT_APP_BACKEND_URL=$BACKEND_URL
      - REACT_APP_FRONTEND_URL=$FRONTEND_URL
      - REACT_APP_SIGNUP_FORM_URL=$SIGNUP_FORM_URL
      - REACT_APP_REQUEST_FORM_URL=$REQUEST_FORM_URL
      - REACT_APP_TWITTER_URL=$TWITTER_URL
      - REACT_APP_BLOG_URL=$BLOG_URL
      - REACT_APP_SUPPORT_EMAIL=$SUPPORT_EMAIL

    stdin_open: true

volumes:
  db-data:
