version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: bash /scripts/deploy/api_deploy.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/backend
      - ./scripts:/scripts
      - ./firebase.json:/backend/quadraticfundingapi/firebase.json
    working_dir: /backend/quadraticfundingapi/
    environment:
      - SENDGRID_KEY=$SENDGRID_KEY
      - PRODUCTION=True
      - STRIPE_KEY=$STRIPE_KEY
      - STRIPE_WEBHOOK_KEY=$STRIPE_WEBHOOK_KEY
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
      - CURRENT_ROUND=1
      - FIREBASE_KEY=$FIREBASE_KEY
      - FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
      - FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL
      - FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
      - FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET
      - FIREBASE_MEASUREMENTID=$FIREBASE_MEASUREMENTID
      - FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID
      - FIREBASE_APPID=$FIREBASE_APPID
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - BACKEND_URL=$BACKEND_URL
      - FRONTEND_URL=$FRONTEND_URL
      - SUPPORT_EMAIL=$SUPPORT_EMAIL
      - ADD_BUSINESS_CSV_TOKEN=$ADD_BUSINESS_CSV_TOKEN
    restart: always

  nginx:
    build:
      context: .
      dockerfile: ./PDockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/downtownapi/static:/var/www/backend
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - ./certs/matchfund.app/fullchain.pem:/etc/letsencrypt/live/matchfund.app/fullchain.pem
      - ./certs/matchfund.app/privkey.pem:/etc/letsencrypt/live/matchfund.app/privkey.pem
    depends_on:
      - api
    restart: always

volumes:
  db-data:
